#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.jsx" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs ./node_modules/.bin/prettier --write

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add


# If git is reporting that your prettified files are still modified
# after committing, you may need to add a post-commit script to
# update git's index as described in this issue.
# see: `pkg-postcommit-update`
#-----------------------------
exit 0
