#!/bin/bash

# -------------------------
# ESLINT
# -------------------------
BASE_PATH="$(npm prefix)"
[[ -f "${BASE_PATH}/./.npmrc" ]] && . ${BASE_PATH}/./.npmrc
NODE_RUN_ENV=
NODE_RUN_FLAGS=
LINT_ARGS="$@"
# ${NODE_RUN_ENV} node ${NODE_RUN_FLAGS}

run_lint () {
  RUN_LINT_ARGS=${1:-'-- ./'}

  echo "lint --config ${BASE_PATH}/.eslintrc.js --ext '.js' --ignore-pattern '!node_modules' ${RUN_LINT_ARGS}"

  ${BASE_PATH}/./node_modules/.bin/eslint \
    --config "${BASE_PATH}/.eslintrc.js" \
    --ext '.js' \
    --ignore-pattern '!node_modules' \
      ${RUN_LINT_ARGS}

}

get_proj_dirs () {
  DEFAULT_DIRS="Config,Life,Model,Screens,Theme,Utilities,Components"
  LINT_DIRS="${1:-$DEFAULT_DIRS}"
  echo ${LINT_DIRS//,/ }
}


if [ "$BASE_PATH" == "$INIT_CWD" ]; then
  run_lint "${LINT_ARGS}"
else
  cd ${INIT_CWD}
  
  run_lint "${LINT_ARGS}"
fi


exit 0
