#!/bin/bash

# -------------
# ROLLUP MODULE BUILDER
# BASE_DIR=$(npm prefix) source ${BASE_DIR}/../.env \
# rollup --format=cjs --preferConst --no-interop --exports named --globals React:react,react-native:react-native --no-esModule $@
# rollup --format=cjs --preferConst --no-interop --exports named --no-esModule $@
# -------------
BASE_DIR="$(npm prefix)"

source ${BASE_DIR}/../.env

rollup \
  --format=cjs \
  --preferConst \
  --no-interop \
  --exports named \
  --no-esModule \
  "$@"
