#!/bin/bash

# find -type f \
#    | grep -i --color google \ # -exec cat {} \;  \
#    | tr -cd "[a-zA-Z0-9!@#$%^&*()_+-=,./<>?:;[]{}\|\s \n]" \
#    | grep -i --color
#
# find . -type f -printf "%G %U %M %m %P \n"
# find . -type f ! -perm 644 -printf "%G %U %M %m %P \n"

TIMEAGO="${1:-}"
BEFORE=${2:-''}
DEPTH="${FIND_MAXDEPTH}"
TYPE="${FIND_TYPE:-'f'}"  # -type f

if [ -z "${TIMEAGO}" ]; then
  echo "find-changed (min)"
  echo "ctime - time when files contents have been modified OR files properties or permissions updated"
  echo "f.changed -<since min ago>|<exactly min|+<more than min>"
  exit 0
fi

SIZE_MIN="${FIND_MINSIZE}" # -size +{MIN_SIZE}
SIZE_MAX="${FIND_MAXSIZE}" # -size -{MAX_SIZE}

LINE_FORMAT="ctime:%CH:%CM:%Cs %M %u %g \033[1m\033[22m\033[00;37m%p\033[0m \033[00;33m%s\033[0m %l \n"
EXCLUDE=""

[[ -n $EXCLUDE_NODE ]] && EXCLUDES="${EXCLUDES} -path "*./node_modules" -prune -o"

find . \
  -type ${TYPE} \
  -cmin ${TIMEAGO} \
  -printf ${LINE_FORMAT}

git diff --dirstat=changes,files
