#!/bin/bash

# UNMET PEER DEPENDENCY react-native-gesture-handler@*
# "invalid"
# "extraneous"
# "err!"
# "peer dep missing"
# "UNMET PEER DEPENDENCY"

npm ls | grep -vi optional | grep -i 'unmet peer'

# |  grep -i --color unmet
# npm ls | grep -vi optional | grep  -i "invalid\|err\|peer\|missing" | sort

#"install-peerdeps"

## List peer dependencies
#npm info react-native@latest peerDependencies
