#!/bin/bash


BASE_PATH="$(npm prefix)"

RUN_LINT_DIRS="src/components,src/config,src/theme,src/util,src/views,src/*.js"
[[ -f "${BASE_PATH}/./.npmrc" ]] && . ${BASE_PATH}/./.npmrc

# pretty:check="${LINT_DIRS}"
LINT_ARGS="$*"

echo "Running linter on project dirs from .npmrc"
echo "${RUN_LINT_DIRS}"

RUN_SCRIPT_PATH="${BASE_PATH}/./node_modules/.bin"

# ${NODE_RUN_ENV} node ${NODE_RUN_FLAGS}

"${RUN_SCRIPT_PATH}/eslint" \
  --config "${BASE_PATH}/.eslintrc.js" \
  --ext ".js" \
  --cache \
  --cache-file "$BASE_PATH/.eslintcache" \
  --ignore-pattern "!node_modules" \
  ${LINT_ARGS} \
      -- \
        ${RUN_LINT_DIRS//,/ }


exit 0
