#!/bin/bash

BASE_PATH="$(npm prefix)"
SYSTEM_APP_DIR="/data/apps"

[[ -f .npmrc ]] && source .npmrc
[[ -f .env ]] && source .env

if [ ! -z $RUN_REACT_REACTOTRON ]; then

  [[ ! -z $APP_REACT_REACTOTRON_RUNNING ]] \
      && echo "React Devtools already running" \

  [[ -z $APP_REACT_REACTOTRON_RUNNING ]] \
      && APP_REACT_REACTOTRON_RUNNING="yes" \
      && ${SYSTEM_APP_DIR}/bin/reactotron &

      ${SYSTEM_APP_DIR}/reactotron/Reactotron.2.17.1.AppImage &
fi

export APP_REACT_REACTOTRON_RUNNING
