#!/bin/bash

BASE_DIR="$(npm prefix)"
APP_DIR="/data/apps"
ABD_PATH="${ANDROID_HOME}/platform-tools"

[[ -f .npmrc ]] && source .npmrc
[[ -f .env ]] && source .env

if [ ! -z $RUN_REACT_REACTOTRON ]; then

  [[ ! -z $APP_REACT_REACTOTRON_RUNNING ]] \
      && echo "React Devtools already running" \

  [[ -z $APP_REACT_REACTOTRON_RUNNING ]] \
      && APP_REACT_REACTOTRON_RUNNING="yes" \
      && ${APP_DIR}/reactotron/Reactotron.2.17.0.AppImage &

fi

export APP_REACT_REACTOTRON_RUNNING
